import 'package:flutter/foundation.dart';
import '../constants/string.dart';
import '../model/category.dart';
import '../model/item.dart';

List<KCategory> categoriesList = [
  KCategory(id: "1", name: "Bag", image: "assets/images/10.png"),
  KCategory(id: "2", name: "Shoes", image: "assets/images/1.png"),
  KCategory(id: "3", name: "Watch", image: "assets/images/2.png"),
  KCategory(id: "4", name: "Bag", image: "assets/images/3.png"),
  KCategory(id: "5", name: "Shoes", image: "assets/images/6.png"),
  KCategory(id: "6", name: "Watch", image: "assets/images/7.png"),
];

List<KItem> itemsList = [
  KItem(
      id: "1",
      name: "Slingback Shoes",
      qty: 25,
      price: 1250,
      discount: .35,
      category: "Shoes",
      image: "assets/images/1.png",
      desc: "Karen Scott Brooke Women's Slingback Shoes in Navy",
      isAsset: true),
  KItem(
      id: "2",
      name: "EMILAB W11L",
      qty: 30,
      price: 3500,
      discount: .20,
      category: "Watch",
      image: "assets/images/2.png",
      desc:
          "EMILAB 1.09 Inch 44mm 3D Display Smart Watch with Fitness Tracker IP68 Water Resistant 15 Days Battery 9 Sports Modes 9 Sports Modes Heart Rate 24 Hours Rose Gold Aluminum Case ESW-W11L-G-GP",
      isAsset: true),
  KItem(
      id: "3",
      name: "laptop bag",
      qty: 12,
      price: 300,
      discount: .5,
      category: "Bag",
      image: "assets/images/3.png",
      desc: "Simple 15 inch laptop bag",
      isAsset: true),
  KItem(
      id: "4",
      name: "Louis Vuitton",
      qty: 35,
      price: 999,
      discount: .65,
      category: "Bag",
      image: "assets/images/4.png",
      desc:
          "Louis Vuitton Canvas Damier Graphite Keepall Bandouliere 45...\nExcellent Condition. Faint exterior scuffing at lining. Faint scratching at hardware. Interior light scuffing and marks.\nComes with a myGemma Certificate Of Authenticity. All of our products are authenticated and certified by our team of luxury experts.",
      isAsset: true),
  KItem(
      id: "5",
      name: "leather shoulder",
      qty: 20,
      price: 450,
      discount: 0,
      category: "Bag",
      image: "assets/images/5.png",
      desc: kItemDescription,
      isAsset: true),
  KItem(
      id: "6",
      name: "Gloria High Heel",
      qty: 15,
      price: 2000,
      discount: .5,
      category: "Shoes",
      image: "assets/images/6.png",
      desc: kItemDescription,
      isAsset: true),
  KItem(
      id: "7",
      name: "Huawei GT-3",
      qty: 7,
      price: 4500,
      discount: .15,
      category: "",
      image: "assets/images/7.png",
      desc: kItemDescription,
      isAsset: true),
  KItem(
      id: "8",
      name: "lace-up sneakers",
      qty: 5,
      price: 500,
      discount: .2,
      category: "Shoes",
      image: "assets/images/8.png",
      desc: kItemDescription,
      isAsset: true),
  KItem(
      id: "10",
      name: "Canvas Tote bag",
      qty: 30,
      price: 780,
      discount: .1,
      category: "bag",
      image: "https://m.media-amazon.com/images/I/71ofdSiPFkL._AC_UX385_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "11",
      name: "Laptop Backpack",
      qty: 2,
      price: 800,
      discount: 0,
      category: "bag",
      image: "https://m.media-amazon.com/images/I/815zOjYlP3L._AC_SY450_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "12",
      name: "tomtoc 14-inch",
      qty: 0,
      price: 1200,
      discount: .5,
      category: "bag",
      image: "https://m.media-amazon.com/images/I/61W9yUMhWdL._AC_SY355_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "13",
      name: "Pleated Hobo",
      qty: 0,
      price: 400,
      discount: .25,
      category: "bag",
      image: "https://m.media-amazon.com/images/I/519yTKyQ6EL._AC_UY500_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "14",
      name: "Walking Slip",
      qty: 5,
      price: 950,
      discount: .12,
      category: "Shoes",
      image: "https://m.media-amazon.com/images/I/51c1Tei29uL._AC_UY395_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "15",
      name: "JENN High-Heels",
      qty: 10,
      price: 490,
      discount: 0,
      category: "Shoes",
      image: "https://m.media-amazon.com/images/I/81UZPLaHQZL._AC_UY395_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "16",
      name: "Lace-Up Loafers",
      qty: 0,
      price: 350,
      discount: .12,
      category: "Shoes",
      image: "https://m.media-amazon.com/images/I/81iwejnkbhL._AC_UY395_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "17",
      name: "ALTRA Trail Running",
      qty: 3,
      price: 800,
      discount: 0,
      category: "Shoes",
      image: "https://m.media-amazon.com/images/I/41dgJ9VigGL._AC_UY395_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "18",
      name: "Toe Loafer",
      qty: 12,
      price: 1500,
      discount: .25,
      category: "Shoes",
      image: "https://m.media-amazon.com/images/I/71N5WdxvcAL._AC_UY395_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "19",
      name: "Loafer Slip",
      qty: 15,
      price: 600,
      discount: .75,
      category: "Shoes",
      image: "https://m.media-amazon.com/images/I/71kX+uLQOzL._AC_UY395_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "20",
      name: "Lightweight Slip",
      qty: 25,
      price: 480,
      discount: 0,
      category: "Shoes",
      image: "https://m.media-amazon.com/images/I/61yhLIob7pL._AC_UX395_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "21",
      name: "Expedition Scout",
      qty: 20,
      price: 1600,
      discount: .10,
      category: "Watch",
      image: "https://m.media-amazon.com/images/I/91APJ9+qs2L._AC_UY500_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "22",
      name: "SYEEKOM Watch",
      qty: 2,
      price: 1200,
      discount: .8,
      category: "Watch",
      image: "https://m.media-amazon.com/images/I/810sEZtbfrL._AC_SY355_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "23",
      name: "Bracelet Watch",
      qty: 3,
      price: 1850,
      discount: .22,
      category: "Watch",
      image: "https://m.media-amazon.com/images/I/61Os8OBwGkL._AC_UX466_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "24",
      name: "AGPTEK Watch",
      qty: 20,
      price: 2300,
      discount: .62,
      category: "Watch",
      image: "https://m.media-amazon.com/images/I/71JfGjxM5lL._AC_SX522_.jpg",
      desc: kItemDescription,
      isAsset: false),
  KItem(
      id: "25",
      name: "Bracelet Watch",
      qty: 15,
      price: 980,
      discount: .15,
      category: "Watch",
      image: "https://m.media-amazon.com/images/I/91s63ccTSJL._AC_UY500_.jpg",
      desc: kItemDescription,
      isAsset: false),
];
